version: "0.2" # yamllint disable-line rule:document-start
phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install -r requirements.txt
      - npm i -g aws-cdk
  build:
    commands:
      - cdk synth
      - cdk deploy '*' --require-approval never
